# Generated by Django 5.1.6 on 2025-02-06 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualexpense',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_expenses', to='app.tag'),
        ),
        migrations.AlterField(
            model_name='annualexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_annual_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_expenses', to='app.tag'),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_general_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_expenses', to='app.tag'),
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_monthly_expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
